/**
 * @fileoverview Core application logic for Chidi.md, a modal Markdown reader and analyzer for OopisOS.
 * This file handles the UI creation, state management, Markdown rendering, and interaction with the Gemini API.
 * @module ChidiApp
 */

const ChidiApp = {
    /**
     * @property {object} state - The current state of the Chidi application.
     */
    state: {
        loadedFiles: [],
        currentIndex: -1,
        isModalOpen: false,
        isAskingMode: false,
        isVerbose: false,
    },

    /**
     * @property {Object.<string, HTMLElement>} elements - A cache of frequently accessed DOM elements.
     */
    elements: {},
    callbacks: {},

    /**
     * Checks if the Chidi modal is currently open and active.
     * @returns {boolean} True if the modal is open, false otherwise.
     */
    isActive() {
        return this.state.isModalOpen;
    },

    /**
     * Launches the Chidi.md application in a modal window.
     * @param {Array<object>} files - An array of file objects ({ name, path, content }) to be loaded.
     * @param {object} callbacks - An object containing onExit and onSaveSession callbacks.
     */
    launch(files, callbacks) {
        if (this.state.isModalOpen) {
            console.warn("ChidiApp is already open.");
            return;
        }

        this.state.isModalOpen = true;
        this.state.loadedFiles = files;
        this.state.currentIndex = files.length > 0 ? 0 : -1;
        this.callbacks = callbacks;

        const chidiElement = this.createModal();
        AppLayerManager.show(chidiElement);

        this.cacheDOMElements();
        this._populateFileDropdown();
        this.setupEventListeners();

        this.updateUI();

        if (callbacks.isNewSession) {
            this.showMessage("New session started. AI interaction history is cleared.");
        } else {
            this.showMessage("Chidi.md initialized. " + files.length + " files loaded.");
        }
    },

    /**
     * Closes the application, removes UI elements and styles, and calls the exit callback.
     */
    close() {
        if (!this.state.isModalOpen) return;

        AppLayerManager.hide();

        this.state = {
            loadedFiles: [],
            currentIndex: -1,
            isModalOpen: false,
            isAskingMode: false,
        };
        this.elements = {};
        this.callbacks = {};

        if (typeof this.callbacks.onExit === 'function') {
            this.callbacks.onExit();
        }
    },

    /**
     * Creates the main modal element containing the application's UI.
     * @returns {HTMLElement} The root element of the Chidi application.
     */
    createModal() {
        const appContainer = document.createElement('div');
        appContainer.id = 'chidi-console-panel';
        appContainer.innerHTML = this.getHTML();
        return appContainer;
    },

    /**
     * Caches references to frequently used DOM elements for performance.
     */
    cacheDOMElements() {
        const get = (id) => document.getElementById(id);
        this.elements = {
            ...this.elements,
            fileSelector: get('chidi-file-selector'),
            summarizeBtn: get('chidi-summarizeBtn'),
            studyBtn: get('chidi-suggestQuestionsBtn'),
            askBtn: get('chidi-askAllFilesBtn'),
            saveSessionBtn: get('chidi-saveSessionBtn'),
            verboseToggleBtn: get('chidi-verbose-toggle-btn'),
            exportBtn: get('chidi-exportBtn'),
            closeBtn: get('chidi-closeBtn'),
            markdownDisplay: get('chidi-markdownDisplay'),
            messageBox: get('chidi-messageBox'),
            loader: get('chidi-loader'),
            mainTitle: get('chidi-mainTitle'),
            fileCountDisplay: get('chidi-fileCountDisplay'),
            askInputContainer: get('chidi-ask-input-container'),
            askInput: get('chidi-ask-input'),
        };
    },

    /**
     * Creates a custom marked.js renderer that adds IDs to headings and normalizes internal links.
     * @returns {marked.Renderer} A new renderer instance.
     */
    _createCustomRenderer() {
        const customRenderer = new marked.Renderer();

        // Override heading to add a slugified ID.
        customRenderer.heading = (text, level, raw) => {
            const slug = Utils.slugify(raw);
            return `<h${level} id="${slug}">${text}</h${level}>`;
        };

        // Override link rendering to normalize internal anchor links.
        customRenderer.link = (href, title, text) => {
            let processedHref = href;
            if (href.startsWith('#')) {
                // Re-slugify the href to match the ID generated by the heading renderer.
                processedHref = '#' + Utils.slugify(href.substring(1));
            }
            // Use the original renderer's logic for the actual tag creation.
            return marked.Renderer.prototype.link.call(this, processedHref, title, text);
        };

        return customRenderer;
    },

    /**
     * Updates the entire UI based on the current application state.
     */
    updateUI() {
        if (!this.state.isModalOpen) return;

        const hasFiles = this.state.loadedFiles.length > 0;
        const currentFile = this.getCurrentFile();

        this.elements.fileCountDisplay.textContent = `FILES: ${this.state.loadedFiles.length}`;
        this.elements.fileSelector.disabled = !hasFiles || this.state.loadedFiles.length <= 1;
        this.elements.exportBtn.disabled = !hasFiles;
        this.elements.saveSessionBtn.disabled = !hasFiles;

        if (hasFiles) {
            this.elements.fileSelector.value = this.state.currentIndex;
        }

        this.elements.summarizeBtn.disabled = !hasFiles;
        this.elements.studyBtn.disabled = !hasFiles;
        this.elements.askBtn.disabled = !hasFiles;

        if (currentFile) {
            this.elements.mainTitle.textContent = currentFile.name.replace(/\.md$/i, '');
            this.elements.markdownDisplay.className = 'chidi-markdown-content'; // Reset class

            const customRenderer = this._createCustomRenderer();

            if (currentFile.name.toLowerCase().endsWith('.txt')) {
                this.elements.markdownDisplay.innerHTML = `<pre>${currentFile.content || ''}</pre>`;
            } else {
                try {
                    this.elements.markdownDisplay.innerHTML = marked.parse(currentFile.content, { renderer: customRenderer });
                } catch (error) {
                    this.elements.markdownDisplay.innerHTML = `<p class="chidi-error-text">Error rendering Markdown for ${currentFile.name}.</p>`;
                    console.error("Markdown parsing error:", error);
                }
            }
        } else {
            this.elements.mainTitle.textContent = "chidi.md";
            this.elements.markdownDisplay.innerHTML = `<p class="chidi-placeholder-text">No files loaded.</p>`;
        }

        this._adjustTitleFontSize();
    },

    _adjustTitleFontSize() {
        const titleEl = this.elements.mainTitle;
        if (!titleEl) return;
        titleEl.style.fontSize = '1.5rem';
        const minFontSize = 0.8;
        let currentFontSize = 1.5;
        while (titleEl.scrollWidth > titleEl.offsetWidth + 1 && currentFontSize > minFontSize) {
            currentFontSize -= 0.05;
            titleEl.style.fontSize = `${currentFontSize}rem`;
        }
    },

    _populateFileDropdown() {
        const selector = this.elements.fileSelector;
        selector.innerHTML = '';
        if (this.state.loadedFiles.length === 0) {
            selector.appendChild(Utils.createElement('option', { textContent: "No Files" }));
            return;
        }
        this.state.loadedFiles.forEach((file, index) => {
            selector.appendChild(Utils.createElement('option', { value: index, textContent: file.name }));
        });
    },

    setupEventListeners() {
        this.elements.closeBtn.addEventListener('click', () => this.close());
        this.elements.exportBtn.addEventListener('click', () => this._handleExport());
        this.elements.saveSessionBtn.addEventListener('click', () => this._handleSaveSession());

        this.elements.verboseToggleBtn.addEventListener('click', () => {
            this.state.isVerbose = !this.state.isVerbose;
            this.elements.verboseToggleBtn.textContent = this.state.isVerbose ? 'Log: On' : 'Log: Off';
            this.showMessage(`Verbose logging ${this.state.isVerbose ? 'enabled' : 'disabled'}.`);
        });

        document.addEventListener('keydown', (e) => {
            if (!this.isActive()) return;
            if (e.key === 'Escape') {
                if (this.state.isAskingMode) {
                    this._exitQuestionMode();
                } else {
                    this.close();
                }
            }
        });

        this.elements.fileSelector.addEventListener('change', (e) => {
            if (this.state.isAskingMode) this._exitQuestionMode();
            this._selectFileByIndex(e.target.value);
        });

        this.elements.summarizeBtn.addEventListener('click', async () => {
            const currentFile = this.getCurrentFile();
            if (!currentFile) return;
            const prompt = `Please provide a concise summary of the following document:\n\n---\n\n${currentFile.content}`;
            this.toggleLoader(true);
            this.showMessage("Contacting Gemini API...");
            const summary = await this.callGeminiApi([{ role: 'user', parts: [{ text: prompt }] }]);
            this.toggleLoader(false);
            this.appendAiOutput("Summary", summary);
        });

        this.elements.studyBtn.addEventListener('click', async () => {
            if (this.state.isAskingMode) {
                this._exitQuestionMode();
                return;
            }
            const currentFile = this.getCurrentFile();
            if (!currentFile) return;
            const prompt = `Based on the following document, what are some insightful questions a user might ask?\n\n---\n\n${currentFile.content}`;
            this.toggleLoader(true);
            this.showMessage("Contacting Gemini API...");
            const questions = await this.callGeminiApi([{ role: 'user', parts: [{ text: prompt }] }]);
            this.toggleLoader(false);
            this.appendAiOutput("Suggested Questions", questions);
        });

        this.elements.askBtn.addEventListener('click', async () => {
            if (this.state.isAskingMode) {
                await this._submitQuestion();
            } else {
                this._enterQuestionMode();
            }
        });

        this.elements.askInput.addEventListener('keydown', async (e) => {
            if (e.key === 'Enter') {
                e.preventDefault();
                await this._submitQuestion();
            }
        });

        this.elements.markdownDisplay.addEventListener('click', (e) => {
            let target = e.target;
            while (target && target.tagName !== 'A') {
                target = target.parentElement;
            }

            if (target && target.getAttribute('href')?.startsWith('#')) {
                e.preventDefault();
                const targetId = target.getAttribute('href').substring(1);
                const targetElement = this.elements.markdownDisplay.querySelector(`#${targetId}`);
                if (targetElement) {
                    targetElement.scrollIntoView({ behavior: 'smooth', block: 'start' });
                }
            }
        });
    },

    _enterQuestionMode() {
        if (!this.getCurrentFile()) return;
        this.state.isAskingMode = true;

        this.elements.markdownDisplay.classList.add('chidi-hidden');
        this.elements.askInputContainer.classList.remove('chidi-hidden');
        this.elements.askInput.value = '';
        this.elements.askInput.focus();

        this.elements.askBtn.textContent = 'Submit';
        this.elements.studyBtn.textContent = 'Cancel';

        this.elements.summarizeBtn.disabled = true;
        this.elements.exportBtn.disabled = true;
        this.elements.fileSelector.disabled = true;

        this.showMessage("Ask a question about all loaded files.");
    },

    _exitQuestionMode() {
        this.state.isAskingMode = false;

        this.elements.askInputContainer.classList.add('chidi-hidden');
        this.elements.markdownDisplay.classList.remove('chidi-hidden');

        this.elements.askBtn.textContent = 'Ask';
        this.elements.studyBtn.textContent = 'Study';

        this.updateUI();

        this.showMessage("Question mode cancelled.");
    },

    async _submitQuestion() {
        const userQuestion = this.elements.askInput.value.trim();
        if (!userQuestion) return;

        this._exitQuestionMode();
        this.toggleLoader(true);
        if (this.state.isVerbose) {
            this.showMessage(`Analyzing ${this.state.loadedFiles.length} files for relevance...`);
        }

        try {
            const questionLower = userQuestion.toLowerCase();
            const stopWords = new Set(['a', 'an', 'the', 'is', 'in', 'of', 'for', 'to', 'what', 'who', 'where', 'when', 'why', 'how', 'and', 'or', 'but']);
            const allWords = questionLower.split(/[\s!"#$%&'()*+,\-./:;<=>?@\[\\\]^_`{|}~]+/).filter(Boolean);
            const keywords = allWords.filter(word => word.length > 2 && !stopWords.has(word));

            const bigrams = [];
            for (let i = 0; i < allWords.length - 1; i++) {
                bigrams.push(allWords[i] + ' ' + allWords[i + 1]);
            }

            if (keywords.length === 0 && bigrams.length === 0) {
                this.toggleLoader(false);
                this.showMessage("Your question is too generic. Please be more specific.");
                this.appendAiOutput("Refine Your Question", "Please ask a more specific question so I can find relevant documents for you.");
                return;
            }

            const currentFile = this.getCurrentFile();
            const otherFiles = this.state.loadedFiles.filter(file => file.path !== currentFile.path);

            const scoredFiles = otherFiles.map(file => {
                let score = 0;
                const contentLower = file.content.toLowerCase();
                const nameLower = file.name.toLowerCase();

                bigrams.forEach(phrase => {
                    score += (contentLower.match(new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g')) || []).length * 10;
                });

                keywords.forEach(keyword => {
                    if (nameLower.includes(keyword)) {
                        score += 15;
                    }
                });

                const headerRegex = /^(#+)\s+(.*)/gm;
                let match;
                while ((match = headerRegex.exec(file.content)) !== null) {
                    const headerText = match[2].toLowerCase();
                    keywords.forEach(keyword => {
                        if (headerText.includes(keyword)) {
                            score += 5;
                        }
                    });
                }

                keywords.forEach(keyword => {
                    score += (contentLower.match(new RegExp(keyword.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g')) || []).length;
                });

                return {
                    file,
                    score
                };
            });

            scoredFiles.sort((a, b) => b.score - a.score);

            const MAX_CONTEXT_FILES = 5;
            const relevantFiles = [currentFile];
            const uniquePaths = new Set([currentFile.path]);

            scoredFiles.slice(0, MAX_CONTEXT_FILES - 1).forEach(item => {
                if (item.score > 0 && !uniquePaths.has(item.file.path)) {
                    relevantFiles.push(item.file);
                    uniquePaths.add(item.file.path);
                }
            });

            if (this.state.isVerbose) {
                this.showMessage(`Found ${relevantFiles.length} relevant files. Asking Gemini...`);
            } else {
                this.showMessage("Asking Gemini...");
            }

            let promptContext = "Based on the following documents, please provide a comprehensive answer to the user's question. Prioritize information from the first document if it is relevant, but use all provided documents to form your answer.\n\n";
            relevantFiles.forEach(file => {
                promptContext += `--- START OF DOCUMENT: ${file.name} ---\n\n${file.content}\n\n--- END OF DOCUMENT: ${file.name} ---\n\n`;
            });

            const finalPrompt = `${promptContext}User's Question: "${userQuestion}"`;

            this.appendAiOutput(
                "Constructed Prompt for Gemini",
                "The following block contains the exact context and question being sent to the AI for analysis.\n\n```text\n" + finalPrompt + "\n```"
            );

            const finalAnswer = await this.callGeminiApi([{
                role: 'user',
                parts: [{
                    text: finalPrompt
                }]
            }]);

            const fileNames = relevantFiles.map(item => item.name).join(', ');
            this.appendAiOutput(`Answer for "${userQuestion}" (based on: ${fileNames})`, finalAnswer || "Could not generate a final answer based on the provided documents.");

        } catch (e) {
            this.showMessage(`An unexpected error occurred: ${e.message}`);
            this.appendAiOutput("Error", `An unexpected error occurred during processing: ${e.message}`);
        } finally {
            this.toggleLoader(false);
        }
    },

    _selectFileByIndex(indexStr) {
        const index = parseInt(indexStr, 10);
        if (!isNaN(index) && index >= 0 && index < this.state.loadedFiles.length) {
            this.state.currentIndex = index;
            this.updateUI();
        }
    },

    getCurrentFile() {
        if (this.state.currentIndex === -1 || this.state.loadedFiles.length === 0) {
            return null;
        }
        return this.state.loadedFiles[this.state.currentIndex];
    },

    showMessage(msg) {
        if (this.elements.messageBox) {
            this.elements.messageBox.textContent = `LOG: ${msg}`;
        }
    },

    appendAiOutput(title, content) {
        const outputBlock = document.createElement('div');
        outputBlock.className = 'chidi-ai-output';
        const customRenderer = this._createCustomRenderer();
        outputBlock.innerHTML = marked.parse(`### ${title}\n\n${content}`, { renderer: customRenderer });
        this.elements.markdownDisplay.appendChild(outputBlock);
        outputBlock.scrollIntoView({
            behavior: 'smooth',
            block: 'start'
        });
        this.showMessage(`AI Response received for "${title}".`);
    },

    toggleLoader(show) {
        if (this.elements.loader) {
            this.elements.loader.classList.toggle('chidi-hidden', !show);
        }
    },

    async callGeminiApi(chatHistory) {
        const apiKey = StorageManager.loadItem(Config.STORAGE_KEYS.GEMINI_API_KEY, "Gemini API Key");
        if (!apiKey) {
            const errorMsg = "API key not found. Please exit and run `chidi` again to set it.";
            this.showMessage(`Error: ${errorMsg}`);
            this.appendAiOutput("API Error", errorMsg);
            return "";
        }

        try {
            const apiUrl = Config.API.GEMINI_URL;
            const headers = {
                'Content-Type': 'application/json',
                'x-goog-api-key': apiKey
            };
            const payload = {
                contents: chatHistory
            };
            const response = await fetch(apiUrl, {
                method: 'POST',
                headers: headers,
                body: JSON.stringify(payload)
            });

            if (!response.ok) {
                const errorBody = await response.json().catch(() => ({
                    error: {
                        message: response.statusText
                    }
                }));
                let errorMsg = `API request failed with status ${response.status}: ${errorBody.error.message}`;
                if (response.status === 400 && errorBody?.error?.message.includes("API key not valid")) {
                    StorageManager.removeItem(Config.STORAGE_KEYS.GEMINI_API_KEY);
                    errorMsg = "Invalid API key. It has been removed. Please exit and run `chidi` again to enter a new one.";
                }
                this.showMessage(`Error: ${errorMsg}`);
                this.appendAiOutput("API Error", `Failed to get a response. Details: ${errorMsg}`);
                return "";
            }

            const result = await response.json();

            if (result.candidates && result.candidates.length > 0) {
                const candidate = result.candidates[0];

                if (candidate.finishReason && candidate.finishReason !== "STOP") {
                    const blockReason = candidate.finishReason;
                    const safetyRatings = candidate.safetyRatings?.map(r => `${r.category}: ${r.probability}`).join(', ') || 'No details';
                    const errorMsg = `Request was blocked. Reason: ${blockReason}. Details: [${safetyRatings}]`;
                    this.showMessage(`Error: ${errorMsg}`);
                    this.appendAiOutput("API Error", errorMsg);
                    return "";
                }

                if (candidate.content && candidate.content.parts) {
                    const fullText = candidate.content.parts.map(part => part.text || "").join("");
                    if (fullText) {
                        this.showMessage("Response received from Gemini.");
                        return fullText;
                    }
                }
            }

            if (result.promptFeedback?.blockReason) {
                const errorMsg = `Request was blocked. Reason: ${result.promptFeedback.blockReason}`;
                this.showMessage(`Error: ${errorMsg}`);
                this.appendAiOutput("API Error", errorMsg);
                return "";
            }

            this.appendAiOutput("API Error", "The AI returned an empty or un-parsable response. The context might be too large or the query unsupported.");
            return "";

        } catch (networkError) {
            this.toggleLoader(false);
            this.showMessage(`Error: ${networkError.message}`);
            this.appendAiOutput("Network Error", networkError.message);
            return "";
        }
    },

    _packageSessionAsHTML() {
        const currentFile = this.getCurrentFile();
        if (!currentFile) return "";

        const content = this.elements.markdownDisplay.innerHTML;
        const title = `Chidi Session: ${currentFile.name}`;
        const styles = `
            body { background-color: #0d0d0d; color: #e4e4e7; font-family: 'VT323', monospace; line-height: 1.6; padding: 2rem; }
            h1, h2, h3, h4, h5, h6 { border-bottom: 1px solid #444; padding-bottom: 0.3rem; color: #60a5fa; }
            a { color: #34d399; }
            pre { white-space: pre-wrap; word-break: break-all; background-color: #000; padding: 1rem; border-radius: 4px; border: 1px solid #333; }
            code:not(pre > code) { background-color: #27272a; color: #facc15; padding: 0.2rem 0.4rem; border-radius: 3px; }
            blockquote { border-left: 4px solid #60a5fa; padding-left: 1rem; margin-left: 0; color: #a1a1aa; }
            .chidi-ai-output { border-top: 2px dashed #60a5fa; margin-top: 2rem; padding-top: 1rem; }
        `;
        return `
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <link href="https://fonts.googleapis.com/css2?family=VT323&display=swap" rel="stylesheet">
                <title>${title}</title>
                <style>${styles}</style>
            </head>
            <body>
                <h1>${title}</h1>
                ${content}
            </body>
            </html>
        `;
    },

    async _handleSaveSession() {
        if (!this.state.isModalOpen || this.state.loadedFiles.length === 0) {
            this.showMessage("Error: No session to save.");
            return;
        }

        const defaultFilename = `chidi_session_${new Date().toISOString().split('T')[0]}.html`;

        const filename = await new Promise(resolve => {
            ModalManager.request({
                context: 'graphical-input',
                messageLines: ["Save Chidi Session As:"],
                placeholder: defaultFilename,
                confirmText: "Save",
                cancelText: "Cancel",
                onConfirm: (value) => resolve(value.trim() || defaultFilename),
                onCancel: () => resolve(null)
            });
        });

        if (!filename) {
            this.showMessage("Save cancelled.");
            return;
        }

        const htmlContent = this._packageSessionAsHTML();
        if (!htmlContent) {
            this.showMessage("Error: Could not package session for saving.");
            return;
        }

        try {
            const absPath = FileSystemManager.getAbsolutePath(filename);
            const currentUser = UserManager.getCurrentUser().name;
            const primaryGroup = UserManager.getPrimaryGroupForUser(currentUser);

            if (!primaryGroup) {
                this.showMessage("Critical Error: Cannot determine primary group. Save failed.");
                return;
            }

            const saveResult = await FileSystemManager.createOrUpdateFile(
                absPath,
                htmlContent,
                { currentUser, primaryGroup }
            );

            if (!saveResult.success) {
                this.showMessage(`Error: ${saveResult.error}`);
                return;
            }

            if (!(await FileSystemManager.save())) {
                this.showMessage("Critical Error: Failed to persist file system changes.");
                return;
            }

            this.showMessage(`Session saved to '${filename}'.`);
        } catch (e) {
            this.showMessage(`An unexpected error occurred during save: ${e.message}`);
        }
    },

    _handleExport() {
        const currentFile = this.getCurrentFile();
        if (!currentFile) {
            this.showMessage("Error: No file to export.");
            return;
        }

        const html = this._packageSessionAsHTML();
        if (!html) return;

        const blob = new Blob([html], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${currentFile.name.replace(/\.(md|txt)$/, '')}_session.html`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        this.showMessage(`Exported session for ${currentFile.name}.`);
    },

    /**
     * Returns the HTML structure for the application modal.
     * @returns {string} The HTML content as a string.
     */
    getHTML() {
        return `
            <div id="chidi-console-panel">
                <header class="chidi-console-header">
                    <h1 id="chidi-mainTitle">chidi.md</h1>
                    <div class="chidi-header-controls">
                        <select id="chidi-file-selector" class="chidi-btn chidi-select"></select>
                        <div class="chidi-control-group">
                            <button id="chidi-summarizeBtn" class="chidi-btn" title="Summarize the current document">Summarize</button>
                            <button id="chidi-suggestQuestionsBtn" class="chidi-btn" title="Suggest questions about the document">Study</button>
                            <button id="chidi-askAllFilesBtn" class="chidi-btn" title="Ask a question across all loaded documents">Ask</button>
                        </div>
                    </div>
                </header>

                <main id="chidi-markdownDisplay" class="chidi-markdown-content">
                    <p class="chidi-placeholder-text">Awaiting file selection...</p>
                </main>

                <div id="chidi-ask-input-container" class="chidi-ask-container chidi-hidden">
                    <textarea id="chidi-ask-input" class="chidi-ask-textarea" placeholder="Ask a question across all loaded documents... (Press Enter to submit)"></textarea>
                </div>
                
                <footer class="chidi-status-readout">
                    <div id="chidi-fileCountDisplay" class="chidi-status-item">FILES: 0</div>
                    <div id="chidi-messageBox" class="chidi-status-message">LOG: Standby.</div>
                    <div class="chidi-control-group">
                        <div id="chidi-loader" class="chidi-loader chidi-hidden"></div>
                        <button id="chidi-verbose-toggle-btn" class="chidi-btn" title="Toggle verbose operation log">Log: Off</button>
                        <button id="chidi-saveSessionBtn" class="chidi-btn" title="Save current session to a new file">Save</button>
                        <button id="chidi-exportBtn" class="chidi-btn" title="Export current view as HTML">Export</button>
                        <button id="chidi-closeBtn" class="chidi-btn chidi-exit-btn" title="Close Chidi (Esc)">Exit</button>
                    </div>
                </footer>
            </div>
        `;
    },
};